### ISSUE TITLE
Dark mode for settings, alert and task panels

### ISSUE THREAD

**Issue by alboz1** [im-mou/quick-scheduler#8]
It seems like when you activate dark mode the settings, alert and the panel that comes down when you click the three dots on the task don't apply dark mode but remain white.

**Comment by im-mou** [comment]
Which browser are you using? Can you try to remove localstorage data and try again and tell if the issue persist?
I wasn't able to recreate the issue on my machine (MacOS HS, Chrome latest)

**Comment by im-mou** [comment]
Oh, I didn't get what you were saying. I still have to create darkmode css rules for the dropdown and other little things. thx

**Comment by im-mou** [comment]
The issue has been solved by @alboz1
